export enum TaonCloudStatus {
  NOT_STARED = 'NOT_STARED',
  KILLING = 'KILLING',
  STARTING_NOT_SECURE_MODE = 'STARTING_NOT_SECURE_MODE',
  STARTING_SECURE_MODE = 'STARTING_SECURE_MODE',
  ENABLED_NOT_SECURE = 'ENABLED_NOT_SECURED',
  ENABLED_SECURED = 'ENABLED_SECURED',
}
